version: "3.8"
services:
  pg:
    image: "postgres:11"
    restart: "always"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=${PG_PASS:?Please set [PG_PASS] in your environment}"
      - "ADMIN_USER=admin"
      - "ADMIN_PASS=${ADMIN_PASS:?Please set [ADMIN_PASS] in your environment}"
      - "FLAG=${FLAG:?Please set [FLAG] in your environment}"
    volumes:
      - "./db/:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
  server:
    build:
      context: "./"
      dockerfile: "./server/Dockerfile"
    restart: always
    environment:
      - "PG_USER=postgres"
      - "PG_PASS=${PG_PASS}"
      - "PG_HOST=pg"
      - "PG_PORT=5432"
    ports:
      - "5000:5000"
